[[constraint]]
  name = "docker.io/go-docker"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
